# Generated by Django 3.2.9 on 2021-11-08 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiToDo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='creatDate',
        ),
    ]
